name: FrontEnd

on:
  push:
    branches:
    - main

jobs:
   ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12]
        
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
 
      - name: Install dependencies
        run: npm install

      - run: lerna run generate

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.studiosvito.com
          username: admindemos@arvi.studiosvito.com
          password: ${{ secrets.passwordAdminDemos }}
          local-dir: packages/demo1/dist/
